# Generated by Django 2.1 on 2025-06-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10, verbose_name='単語')),
                ('length', models.IntegerField(verbose_name='文字数')),
                ('active', models.BooleanField(default=True, verbose_name='正解可否')),
            ],
            options={
                'db_table': 'word',
            },
        ),
    ]
