# Generated by Django 2.1 on 2025-06-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='text',
        ),
        migrations.AddField(
            model_name='word',
            name='expression',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='漢字'),
        ),
        migrations.AddField(
            model_name='word',
            name='reading',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ひらがな'),
        ),
    ]
