# Generated by Django 2.1 on 2025-06-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_auto_20250612_0951'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='word',
            table='word_jlpt',
        ),
    ]
