# Generated by Django 2.1 on 2025-06-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_auto_20250612_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='expression',
            field=models.CharField(max_length=10, verbose_name='漢字'),
        ),
        migrations.AlterField(
            model_name='word',
            name='reading',
            field=models.CharField(max_length=10, verbose_name='ひらがな'),
        ),
    ]
