# Generated by Django 2.1 on 2025-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0004_auto_20250612_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='タグ'),
        ),
    ]
