# Generated by Django 2.1 on 2025-06-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0005_word_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.CharField(blank=True, max_length=255, verbose_name='意味'),
        ),
    ]
