# Generated by Django 2.1 on 2025-06-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0006_word_meaning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='tag',
            new_name='tags',
        ),
    ]
